In [1]:
import pandas as pd
import numpy as np
import warnings
## Data Visualization
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_bank = pd.read_csv('https://raw.githubusercontent.com/rafiag/DTI2020/main/data/bank.csv')

# Drop 'duration' column
df_bank = df_bank.drop('duration', axis=1)

# print(df_bank.info())
print('Shape of dataframe:', df_bank.shape)
df_bank.head()

Shape of dataframe: (11162, 16)


age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  campaign  pdays  previous poutcome deposit  
0    5   may         1     -1         0  unknown     yes  
1    5   may         1     -1         0  unknown     yes  
2    5   may         1     -1         0  unknown     yes  
3    5   may         1     -1         0  unknown     yes  
4    5   may         2     -1         0  unknown     yes

In [3]:
df_bank['deposit'].value_counts()

deposit
no     5873
yes    5289
Name: count, dtype: int64

In [4]:
df_bank.isnull().sum()


age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [6]:
from sklearn.preprocessing import StandardScaler

# Copying original dataframe
df_bank_ready = df_bank.copy()

scaler = StandardScaler()
num_cols = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
df_bank_ready[num_cols] = scaler.fit_transform(df_bank[num_cols])

df_bank_ready.head()

age         job  marital  education default   balance housing loan  \
0  1.491505      admin.  married  secondary      no  0.252525     yes   no   
1  1.239676      admin.  married  secondary      no -0.459974      no   no   
2 -0.019470  technician  married  secondary      no -0.080160     yes   no   
3  1.155733    services  married  secondary      no  0.293762     yes   no   
4  1.071790      admin.  married   tertiary      no -0.416876      no   no   

   contact       day month  campaign     pdays  previous poutcome deposit  
0  unknown -1.265746   may -0.554168 -0.481184  -0.36326  unknown     yes  
1  unknown -1.265746   may -0.554168 -0.481184  -0.36326  unknown     yes  
2  unknown -1.265746   may -0.554168 -0.481184  -0.36326  unknown     yes  
3  unknown -1.265746   may -0.554168 -0.481184  -0.36326  unknown     yes  
4  unknown -1.265746   may -0.186785 -0.481184  -0.36326  unknown     yes

In [14]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Assuming df_bank_ready is your DataFrame
encoder = OneHotEncoder(sparse_output=False)

# Categorical columns to be encoded
cat_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

# Encode categorical data
df_encoded = pd.DataFrame(encoder.fit_transform(df_bank_ready[cat_cols]))

# Set column names for the encoded columns using get_feature_names_out
df_encoded.columns = encoder.get_feature_names_out(cat_cols)

# Replace categorical data with encoded data
df_bank_ready = df_bank_ready.drop(cat_cols, axis=1)
df_bank_ready = pd.concat([df_encoded, df_bank_ready], axis=1)

# Encode the target value (deposit)
df_bank_ready['deposit'] = df_bank_ready['deposit'].apply(lambda x: 1 if x == 'yes' else 0)

# Print the shape of the resulting dataframe
print('Shape of dataframe:', df_bank_ready.shape)

# Display the first few rows
df_bank_ready.head()


Shape of dataframe: (11162, 51)


job_admin.  job_blue-collar  job_entrepreneur  job_housemaid  \
0         1.0              0.0               0.0            0.0   
1         1.0              0.0               0.0            0.0   
2         0.0              0.0               0.0            0.0   
3         0.0              0.0               0.0            0.0   
4         1.0              0.0               0.0            0.0   

   job_management  job_retired  job_self-employed  job_services  job_student  \
0             0.0          0.0                0.0           0.0          0.0   
1             0.0          0.0                0.0           0.0          0.0   
2             0.0          0.0                0.0           0.0          0.0   
3             0.0          0.0                0.0           1.0          0.0   
4             0.0          0.0                0.0           0.0          0.0   

   job_technician  ...  poutcome_other  poutcome_success  poutcome_unknown  \
0             0.0  ...             0.0               0.0               1.0   
1             0.0  ...             0.0               0.0               1.0   
2             1.0  ...             0.0               0.0               1.0   
3             0.0  ...             0.0               0.0               1.0   
4             0.0  ...             0.0               0.0               1.0   

        age   balance       day  campaign     pdays  previous  deposit  
0  1.491505  0.252525 -1.265746 -0.554168 -0.481184  -0.36326        1  
1  1.239676 -0.459974 -1.265746 -0.554168 -0.481184  -0.36326        1  
2 -0.019470 -0.080160 -1.265746 -0.554168 -0.481184  -0.36326        1  
3  1.155733  0.293762 -1.265746 -0.554168 -0.481184  -0.36326        1  
4  1.071790 -0.416876 -1.265746 -0.186785 -0.481184  -0.36326        1  

[5 rows x 51 columns]

In [15]:

# Select Features
feature = df_bank_ready.drop('deposit', axis=1)

# Select Target
target = df_bank_ready['deposit']

# Set Training and Testing Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature , target, 
                                                    shuffle = True, 
                                                    test_size=0.2, 
                                                    random_state=1)

# Show the Training and Testing Data
print('Shape of training feature:', X_train.shape)
print('Shape of testing feature:', X_test.shape)
print('Shape of training label:', y_train.shape)
print('Shape of training label:', y_test.shape)

Shape of training feature: (8929, 50)
Shape of testing feature: (2233, 50)
Shape of training label: (8929,)
Shape of training label: (2233,)


In [16]:
def evaluate_model(model, x_test, y_test):
    from sklearn import metrics

    # Predict Test Data 
    y_pred = model.predict(x_test)

    # Calculate accuracy, precision, recall, f1-score, and kappa score
    acc = metrics.accuracy_score(y_test, y_pred)
    prec = metrics.precision_score(y_test, y_pred)
    rec = metrics.recall_score(y_test, y_pred)
    f1 = metrics.f1_score(y_test, y_pred)
    kappa = metrics.cohen_kappa_score(y_test, y_pred)

    # Calculate area under curve (AUC)
    y_pred_proba = model.predict_proba(x_test)[::,1]
    fpr, tpr, _ = metrics.roc_curve(y_test, y_pred_proba)
    auc = metrics.roc_auc_score(y_test, y_pred_proba)

    # Display confussion matrix
    cm = metrics.confusion_matrix(y_test, y_pred)

    return {'acc': acc, 'prec': prec, 'rec': rec, 'f1': f1, 'kappa': kappa, 
            'fpr': fpr, 'tpr': tpr, 'auc': auc, 'cm': cm}

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Diviser les données en ensembles de train et test
x_train, x_test, y_train, y_test = train_test_split(df_bank_ready.drop('deposit', axis=1), 
                                                    df_bank_ready['deposit'], 
                                                    test_size=0.2, 
                                                    random_state=42)

# Entraîner le modèle
model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)


RandomForestClassifier(random_state=42)

In [19]:
model_results = evaluate_model(model, x_test, y_test)

print("Accuracy: ", model_results['acc'])
print("Precision: ", model_results['prec'])
print("Recall: ", model_results['rec'])
print("F1-Score: ", model_results['f1'])
print("Cohen's Kappa: ", model_results['kappa'])
print("AUC: ", model_results['auc'])
print("Confusion Matrix: \n", model_results['cm'])


Accuracy:  0.7335423197492164
Precision:  0.7582056892778993
Recall:  0.6494845360824743
F1-Score:  0.6996466431095406
Cohen's Kappa:  0.46276470352760124
AUC:  0.7802000125389632
Confusion Matrix: 
 [[945 221]
 [374 693]]


In [20]:
from sklearn import tree

# Building Decision Tree model 
dtc = tree.DecisionTreeClassifier(random_state=0)
dtc.fit(X_train, y_train)

# Evaluate Model
dtc_eval = evaluate_model(dtc, X_test, y_test)

# Print result
print('Accuracy:', dtc_eval['acc'])
print('Precision:', dtc_eval['prec'])
print('Recall:', dtc_eval['rec'])
print('F1 Score:', dtc_eval['f1'])
print('Cohens Kappa Score:', dtc_eval['kappa'])
print('Area Under Curve:', dtc_eval['auc'])
print('Confusion Matrix:\n', dtc_eval['cm'])

Accuracy: 0.49216300940438873
Precision: 0.4690101757631822
Recall: 0.4751640112464855
F1 Score: 0.4720670391061452
Cohens Kappa Score: -0.017107763000927756
Area Under Curve: 0.49144135382221354
Confusion Matrix:
 [[592 574]
 [560 507]]


In [21]:
from sklearn import tree

# Building Decision Tree model 
dtc = tree.DecisionTreeClassifier(random_state=0)
dtc.fit(X_train, y_train)

# Evaluate Model
dtc_eval = evaluate_model(dtc, X_test, y_test)

# Print result
print('Accuracy:', dtc_eval['acc'])
print('Precision:', dtc_eval['prec'])
print('Recall:', dtc_eval['rec'])
print('F1 Score:', dtc_eval['f1'])
print('Cohens Kappa Score:', dtc_eval['kappa'])
print('Area Under Curve:', dtc_eval['auc'])
print('Confusion Matrix:\n', dtc_eval['cm'])

Accuracy: 0.49216300940438873
Precision: 0.4690101757631822
Recall: 0.4751640112464855
F1 Score: 0.4720670391061452
Cohens Kappa Score: -0.017107763000927756
Area Under Curve: 0.49144135382221354
Confusion Matrix:
 [[592 574]
 [560 507]]


In [ ]:
from sklearn.model_selection import GridSearchCV

# Create the parameter grid based on the results of random search 
param_grid = {
    'max_depth': [50, 80, 100],
    'max_features': [2, 3, 4],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 300, 500, 750, 1000]
}

# Create a base model
rf_grids = RandomForestClassifier(random_state=0)

# Initiate the grid search model
grid_search = GridSearchCV(estimator=rf_grids, param_grid=param_grid, scoring='recall',
                           cv=5, n_jobs=-1, verbose=2)

# Fit the grid search to the data
grid_search.fit(X_train, y_train)

grid_search.best_params_

Fitting 5 folds for each of 405 candidates, totalling 2025 fits


In [ ]:
# Select best model with best fit
best_grid = grid_search.best_estimator_

# Evaluate Model
best_grid_eval = evaluate_model(best_grid, X_test, y_test)

# Print result
print('Accuracy:', best_grid_eval['acc'])
print('Precision:', best_grid_eval['prec'])
print('Recall:', best_grid_eval['rec'])
print('F1 Score:', best_grid_eval['f1'])
print('Cohens Kappa Score:', best_grid_eval['kappa'])
print('Area Under Curve:', best_grid_eval['auc'])
print('Confusion Matrix:\n', best_grid_eval['cm'])

In [ ]:
df_bank['deposit_prediction'] = rf.predict(feature)
df_bank['deposit_prediction'] = df_bank['deposit_prediction'].apply(lambda x: 'yes' if x==0 else 'no')

# Save new dataframe into csv file
df_bank.to_csv('deposit_prediction.csv', index=False)

df_bank.head(10)

In [ ]:
from joblib import dump, load

# Saving model
dump(rf, 'bank_deposit_classification.joblib')
# Loading model
clf = load('bank_deposit_classification.joblib') 